name = "final-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  { pattern = "afrcloud.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "df.game.naver.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "zoomgov.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "api24-normal-alisg.tiktokv.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "help.viu.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "grabacademyportal.grab.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "api22-normal-c-alisg.tiktokv.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "live.iflix.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "store.linefriends.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.biz.id", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.afrcloud.biz.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "f0551657c81945bcb9fd4e6c9f2ee60e"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/SirenWeb/refs/heads/main/web/converter.html"
